version: "3.9"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "1215:1215"
  mysql:
    image: "mysql:8.0"
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - ./src:/var/www/html
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/html
#  swoole:
#    build:
#      context: dockerfiles
#      dockerfile: php.Dockerfile
#    container_name: swoole
#    ports:
#      - "1215:1215"
#    volumes:
#      - ./src:/var/www/html:delegated
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
